[package]
name = "ffmpegrust-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
avcodec = { path = "../crates/avcodec" }
avformat = { path = "../crates/avformat" }
avutil = { path = "../crates/avutil" }
fftools = { path = "../crates/fftools" }
libfuzzer-sys = "0.4"

[[bin]]
name = "avcodec_basic_decoders"
path = "fuzz_targets/avcodec_basic_decoders.rs"
test = false
doc = false
bench = false

[[bin]]
name = "avutil_byteio"
path = "fuzz_targets/avutil_byteio.rs"
test = false
doc = false
bench = false

[[bin]]
name = "avutil_bitreader"
path = "fuzz_targets/avutil_bitreader.rs"
test = false
doc = false
bench = false

[[bin]]
name = "avutil_metadata_options"
path = "fuzz_targets/avutil_metadata_options.rs"
test = false
doc = false
bench = false

[[bin]]
name = "avutil_core_models"
path = "fuzz_targets/avutil_core_models.rs"
test = false
doc = false
bench = false

[[bin]]
name = "avformat_wav"
path = "fuzz_targets/avformat_wav.rs"
test = false
doc = false
bench = false

[[bin]]
name = "avformat_probe"
path = "fuzz_targets/avformat_probe.rs"
test = false
doc = false
bench = false

[[bin]]
name = "avformat_yuv4mpegpipe"
path = "fuzz_targets/avformat_yuv4mpegpipe.rs"
test = false
doc = false
bench = false

[[bin]]
name = "avformat_pcm_s16le"
path = "fuzz_targets/avformat_pcm_s16le.rs"
test = false
doc = false
bench = false

[[bin]]
name = "avformat_rawvideo"
path = "fuzz_targets/avformat_rawvideo.rs"
test = false
doc = false
bench = false

[[bin]]
name = "avformat_avi"
path = "fuzz_targets/avformat_avi.rs"
test = false
doc = false
bench = false

[[bin]]
name = "avformat_avi_muxer"
path = "fuzz_targets/avformat_avi_muxer.rs"
test = false
doc = false
bench = false

[[bin]]
name = "avformat_mov"
path = "fuzz_targets/avformat_mov.rs"
test = false
doc = false
bench = false

[[bin]]
name = "avformat_image2"
path = "fuzz_targets/avformat_image2.rs"
test = false
doc = false
bench = false

[[bin]]
name = "avformat_basic_muxers"
path = "fuzz_targets/avformat_basic_muxers.rs"
test = false
doc = false
bench = false

[[bin]]
name = "avformat_packet_muxers"
path = "fuzz_targets/avformat_packet_muxers.rs"
test = false
doc = false
bench = false

[[bin]]
name = "fftools_option_parser"
path = "fuzz_targets/fftools_option_parser.rs"
test = false
doc = false
bench = false

[workspace]
