[package]
name = "ffmpegrust-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
avformat = { path = "../crates/avformat" }
avutil = { path = "../crates/avutil" }
libfuzzer-sys = "0.4"

[[bin]]
name = "avutil_byteio"
path = "fuzz_targets/avutil_byteio.rs"
test = false
doc = false
bench = false

[[bin]]
name = "avutil_bitreader"
path = "fuzz_targets/avutil_bitreader.rs"
test = false
doc = false
bench = false

[[bin]]
name = "avformat_wav"
path = "fuzz_targets/avformat_wav.rs"
test = false
doc = false
bench = false

[[bin]]
name = "avformat_yuv4mpegpipe"
path = "fuzz_targets/avformat_yuv4mpegpipe.rs"
test = false
doc = false
bench = false

[[bin]]
name = "avformat_pcm_s16le"
path = "fuzz_targets/avformat_pcm_s16le.rs"
test = false
doc = false
bench = false

[[bin]]
name = "avformat_rawvideo"
path = "fuzz_targets/avformat_rawvideo.rs"
test = false
doc = false
bench = false

[workspace]
